### ISSUE TITLE
Failing tests and vulnerable dependencies

### ISSUE THREAD

**Issue by eoftedal** [leandrob/saml20#21]
`npm audit`
```
[!] 9 vulnerabilities found - Packages audited: 61 (52 dev, 0 optional)
    Severity: 4 low | 1 moderate | 3 high | 1 critical
```
`npm run test`
```
  14 passing (276ms)
  2 failing

  1) lib.saml11 Should validate saml 1.1 token using thumbprint:
     Error: Invalid assertion signature.
      at Object.validate (lib/index.js:53:6)
      at Context.<anonymous> (test/lib.saml11.js:17:8)

  2) lib.saml20 Should validate saml 2.0 token using thumbprint:
     Error: Invalid assertion signature.
      at Object.validate (lib/index.js:53:6)
      at Context.<anonymous> (test/lib.saml20.js:17:8)
```

**Comment by ariellyciandt** [comment]
Hello there,

Any updates regarding this ticket? 

Thanks.
